"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import AppShell from "@/components/AppShell";
import ConfirmModal from "@/components/ConfirmModal";
import { ApiError, activateWorker, createWorker, deactivateWorker, deleteWorker, fetchHealth, fetchWorkers, loadSettings, regenerateWorkerToken, renameWorker, type HealthResponse, type ProcessingWorker } from "@/lib/api";

function Card({children,className=""}:{children:React.ReactNode;className?:string}){return <section className={`rounded-2xl border border-line bg-white p-5 shadow-sm ${className}`}>{children}</section>}
function Pill({ok,label}:{ok:boolean;label:string}){return <span className={`rounded-full px-2 py-1 text-[10px] font-semibold ${ok?"bg-sage/10 text-sage":"bg-brick/10 text-brick"}`}>{ok?"✓":"!"} {label}</span>}
function online(w:ProcessingWorker){return !!w.last_seen && (Date.now()-new Date(w.last_seen).getTime()) < 45_000}

export default function WorkersPage(){
 const s=loadSettings();
 const [workers,setWorkers]=useState<ProcessingWorker[]>([]),[health,setHealth]=useState<HealthResponse|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);
 const [createOpen,setCreateOpen]=useState(false),[name,setName]=useState(""),[workerId,setWorkerId]=useState("");
 const [credential,setCredential]=useState<{worker:ProcessingWorker;token:string}|null>(null);
 const [copied,setCopied]=useState<"token"|"setup"|null>(null);
 const [rename,setRename]=useState<ProcessingWorker|null>(null),[renameName,setRenameName]=useState("");
 const [confirm,setConfirm]=useState<{type:"activate"|"deactivate"|"delete";worker:ProcessingWorker}|null>(null);
 const load=useCallback(async()=>{if(!s.baseUrl)return;try{const [w,h]=await Promise.all([fetchWorkers(s),fetchHealth(s)]);setWorkers(w.items);setHealth(h);setError(null)}catch(e){setError(e instanceof ApiError?e.message:"Could not load worker status.")}},[]);
 useEffect(()=>{void load();const id=setInterval(()=>void load(),5000);return()=>clearInterval(id)},[load]);
 const activeWorkers=useMemo(()=>workers.filter(w=>w.active),[workers]);
 const doAction=async(fn:()=>Promise<unknown>)=>{setBusy(true);try{await fn();await load()}catch(e){setError(e instanceof ApiError?e.message:"Worker action failed.")}finally{setBusy(false)}};
 const submitCreate=async()=>{if(!name.trim()||!workerId.trim())return;setBusy(true);try{const r=await createWorker(s,{name:name.trim(),worker_id:workerId.trim()});setCredential(r);setCreateOpen(false);setName("");setWorkerId("");await load()}catch(e){setError(e instanceof ApiError?e.message:"Could not create worker.")}finally{setBusy(false)}};
 const saveRename=async()=>{if(!rename||!renameName.trim())return;await doAction(()=>renameWorker(s,rename.worker_id,renameName.trim()));setRename(null)};
 const setup=`PICD_CLOUD_API_URL=${s.baseUrl || "https://backend.picds-manual.com"}\nPROCESSING_AGENT_TOKEN=${credential?.token || "<worker token>"}\nPROCESSING_AGENT_ID=${credential?.worker.worker_id || "<worker-id>"}\nPROCESSING_AGENT_POLL_SECONDS=2\nPROCESSING_AGENT_HEARTBEAT_SECONDS=30`;
 const copy=async(text:string,kind:"token"|"setup")=>{
  try{
   await navigator.clipboard.writeText(text);
   setCopied(kind);
   window.setTimeout(()=>setCopied(null),1800);
  }catch{
   setError("Could not copy to the clipboard. Please allow clipboard access in your browser and try again.");
  }
 };
 return <AppShell><div className="h-full overflow-y-auto bg-paper px-8 py-6"><div className="mx-auto max-w-7xl">
  <header className="mb-6 flex items-end justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-ink/30">Control</p><h1 className="mt-1 font-display text-3xl font-semibold">Processing workers</h1><p className="mt-1 text-sm text-ink/45">Manage every Photoshop / Illustrator / DAZ computer from one place.</p></div><div className="flex gap-2"><button onClick={()=>setCreateOpen(true)} className="rounded-xl bg-blueprint px-4 py-2.5 text-xs font-semibold text-paper">＋ Add worker</button><button onClick={()=>void load()} className="rounded-xl border border-line bg-white px-4 py-2.5 text-xs font-semibold text-ink/60 shadow-sm">Refresh</button></div></header>
  {error&&<div className="mb-5 rounded-xl border border-brick/20 bg-brick/10 px-4 py-3 text-sm text-brick">{error}</div>}
  <div className="mb-5 grid grid-cols-4 gap-3"><Card><p className="text-[10px] uppercase tracking-widest text-ink/35">Enabled workers</p><p className="mt-2 font-display text-xl font-semibold">{activeWorkers.length ? `${activeWorkers.length} enabled` : "None enabled"}</p></Card><Card><p className="text-[10px] uppercase tracking-widest text-ink/35">Online</p><p className="mt-2 font-display text-2xl font-semibold">{workers.filter(online).length}<span className="text-sm font-normal text-ink/30"> / {workers.length}</span></p></Card><Card><p className="text-[10px] uppercase tracking-widest text-ink/35">Queue depth</p><p className="mt-2 font-display text-2xl font-semibold">{health?.queue_depth??"—"}</p></Card><Card><p className="text-[10px] uppercase tracking-widest text-ink/35">Processing</p><p className="mt-2 font-display text-2xl font-semibold">{health?.processing?"Yes":"No"}</p></Card></div>
  <Card className="mb-4"><div className="flex items-start justify-between"><div><h2 className="font-display font-semibold">Worker pool</h2><p className="mt-1 text-xs text-ink/40">Any enabled worker can claim a released scan. Multiple workers can process the queue in parallel; standby workers stay connected without claiming jobs.</p></div><Pill ok={activeWorkers.length>0} label={activeWorkers.length?`${activeWorkers.length} enabled`:"No workers enabled"}/></div>
   <div className="mt-5 space-y-3">{workers.length===0?<div className="rounded-xl border border-dashed border-line px-5 py-10 text-center text-sm text-ink/35">No processing workers yet. Add the first Photoshop/Illustrator/DAZ computer.</div>:workers.map(w=><div key={w.worker_id} className={`rounded-2xl border p-4 ${w.active?"border-blueprint/30 bg-blueprint/[.03]":"border-line bg-white"}`}>
    <div className="flex items-center gap-4"><div className={`h-3 w-3 rounded-full ${online(w)?"bg-sage":"bg-ink/15"}`}/><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><b className="font-display">{w.name}</b>{w.active&&<span className="rounded-full bg-sage/10 px-2 py-1 text-[9px] font-bold uppercase tracking-widest text-sage">ENABLED</span>}<span className="text-[10px] font-mono text-ink/30">{w.worker_id}</span></div><div className="mt-1 flex gap-4 text-[11px] text-ink/40"><span>{online(w)?"Online":"Offline"}</span><span>{w.last_seen?`Last seen ${new Date(w.last_seen).toLocaleTimeString()}`:"Never connected"}</span><span>{w.processed_count} completed</span>{w.current_scan_id&&<span>Processing {w.current_scan_id.slice(0,12)}…</span>}</div></div><div className="flex gap-2"><button onClick={()=>{setRename(w);setRenameName(w.name)}} className="rounded-lg border border-line px-3 py-2 text-[11px] font-semibold">Rename</button>{w.active?<button disabled={busy} onClick={()=>setConfirm({type:"deactivate",worker:w})} className="rounded-lg border border-line px-3 py-2 text-[11px] font-semibold">Disable</button>:<button disabled={busy} onClick={()=>setConfirm({type:"activate",worker:w})} className="rounded-lg bg-blueprint px-3 py-2 text-[11px] font-semibold text-paper">Enable processing</button>}<button disabled={busy||w.active} onClick={()=>setConfirm({type:"delete",worker:w})} className="rounded-lg border border-brick/20 px-3 py-2 text-[11px] font-semibold text-brick disabled:opacity-30">Delete</button></div></div>
   </div>)}</div>
  </Card>
  <div className="grid grid-cols-2 gap-4"><Card><h2 className="font-display font-semibold">Worker credentials</h2><p className="mt-1 text-xs leading-relaxed text-ink/40">Tokens are stored hashed on the server and are shown only when a worker is created or its key is regenerated. Never put a worker token in the frontend code or Git.</p><div className="mt-4 rounded-xl bg-ink/[.03] p-4 text-xs"><div className="flex justify-between"><span className="text-ink/40">Enabled workers</span><b>{activeWorkers.length ? activeWorkers.map(w=>w.name).join(", ") : "None"}</b></div><div className="mt-2 flex justify-between"><span className="text-ink/40">Agent mode</span><b>Remote desktop</b></div></div></Card><Card><h2 className="font-display font-semibold">Release policy</h2><div className="mt-4 space-y-2 text-xs"><div className="flex justify-between rounded-xl bg-ink/[.03] px-4 py-3"><span className="text-ink/50">Automatic processing</span><b>Disabled</b></div><div className="flex justify-between rounded-xl bg-ink/[.03] px-4 py-3"><span className="text-ink/50">Manual release</span><b>Enabled</b></div><div className="flex justify-between rounded-xl bg-ink/[.03] px-4 py-3"><span className="text-ink/50">Enabled workers receive jobs</span><b>Yes</b></div></div></Card></div>
 </div></div>
 {createOpen&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-ink/30"><div className="w-[520px] rounded-2xl border border-line bg-white p-6 shadow-2xl"><h2 className="font-display text-xl font-semibold">Add processing worker</h2><p className="mt-1 text-xs text-ink/40">Create a named computer identity and generate its private agent key.</p><label className="mt-5 block text-xs font-semibold">Worker name<input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Michael's PC" className="mt-2 w-full rounded-xl border border-line px-3 py-3 text-sm outline-none" name="field_page_1"/></label><label className="mt-4 block text-xs font-semibold">Worker ID<input value={workerId} onChange={e=>setWorkerId(e.target.value.toLowerCase().replace(/[^a-z0-9._-]/g,"-"))} placeholder="e.g. michael-pc" className="mt-2 w-full rounded-xl border border-line px-3 py-3 text-sm font-mono outline-none" name="field_page_2"/></label><div className="mt-5 flex justify-end gap-2"><button onClick={()=>setCreateOpen(false)} className="rounded-xl border border-line px-4 py-2.5 text-xs font-semibold">Cancel</button><button disabled={busy||!name.trim()||!workerId.trim()} onClick={()=>void submitCreate()} className="rounded-xl bg-blueprint px-4 py-2.5 text-xs font-semibold text-paper disabled:opacity-40">Generate worker key</button></div></div></div>}
 {credential&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-ink/30"><div className="w-[680px] rounded-2xl border border-line bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-[10px] font-bold uppercase tracking-widest text-sage">Key generated</p><h2 className="mt-1 font-display text-xl font-semibold">{credential.worker.name}</h2><p className="mt-1 text-xs text-ink/40">Copy this token now. The server will not display it again.</p></div><button onClick={()=>setCredential(null)} className="text-ink/30">✕</button></div><div className="mt-5 rounded-xl border border-brick/20 bg-brick/[.04] p-4"><p className="text-[10px] font-bold uppercase tracking-widest text-brick">Private worker token</p><code className="mt-2 block break-all text-xs">{credential.token}</code></div><div className="mt-4"><p className="mb-2 text-xs font-semibold">Agent .env setup</p><pre className="overflow-auto rounded-xl bg-ink/[.04] p-4 text-[11px] leading-relaxed">{setup}</pre></div><div className="mt-5 flex items-center justify-between gap-3">
 <div className={`text-xs font-semibold transition-opacity ${copied?"opacity-100":"opacity-0"}`} aria-live="polite">{copied?`✓ ${copied==="token"?"Token":"Setup"} copied to clipboard`:"Copied"}</div>
 <div className="flex gap-2">
  <button onClick={()=>void copy(credential.token,"token")} className={`rounded-xl border px-4 py-2.5 text-xs font-semibold ${copied==="token"?"border-sage/30 bg-sage/10 text-sage":"border-line"}`}>{copied==="token"?"✓ Copied":"Copy token"}</button>
  <button onClick={()=>void copy(setup,"setup")} className={`rounded-xl px-4 py-2.5 text-xs font-semibold ${copied==="setup"?"bg-sage text-paper":"bg-blueprint text-paper"}`}>{copied==="setup"?"✓ Copied":"Copy setup"}</button>
 </div>
</div></div></div>}
 {rename&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-ink/30"><div className="w-[460px] rounded-2xl border border-line bg-white p-6 shadow-2xl"><h2 className="font-display text-xl font-semibold">Rename worker</h2><input value={renameName} onChange={e=>setRenameName(e.target.value)} className="mt-4 w-full rounded-xl border border-line px-3 py-3 text-sm outline-none" name="field_page_3"/><div className="mt-5 flex justify-end gap-2"><button onClick={()=>setRename(null)} className="rounded-xl border border-line px-4 py-2.5 text-xs font-semibold">Cancel</button><button disabled={busy||!renameName.trim()} onClick={()=>void saveRename()} className="rounded-xl bg-blueprint px-4 py-2.5 text-xs font-semibold text-paper">Save</button></div></div></div>}
 <ConfirmModal open={!!confirm} title={confirm?.type==="activate"?`Enable ${confirm.worker.name} for processing?`:confirm?.type==="deactivate"?`Disable ${confirm.worker.name}?`:`Delete ${confirm?.worker.name}?`} message={confirm?.type==="activate"?"This worker will be allowed to claim newly released scans. Other enabled workers remain active too.":confirm?.type==="deactivate"?"This worker will stop receiving new jobs. A scan already running will finish.":"This removes the worker identity and invalidates its token. The computer will no longer be able to connect."} confirmLabel="Confirm" busy={busy} onConfirm={()=>{if(!confirm)return;const c=confirm;setConfirm(null);const fn=c.type==="activate"?()=>activateWorker(s,c.worker.worker_id):c.type==="deactivate"?()=>deactivateWorker(s,c.worker.worker_id):()=>deleteWorker(s,c.worker.worker_id);void doAction(fn)}} onCancel={()=>!busy&&setConfirm(null)}/>
 </AppShell>;
}
