"use client";
import { useCallback, useEffect, useState } from "react";
import AppShell from "@/components/AppShell";
import ConfirmModal from "@/components/ConfirmModal";
import { ApiError, fetchAudit, fetchHealth, fetchSystemState, loadSettings, updateSystemControl, type HealthResponse, type SystemRow, type SystemState } from "@/lib/api";
function Card({children}:{children:React.ReactNode}){return <section className="rounded-2xl border border-line bg-white p-5 shadow-sm">{children}</section>}
function Pill({ok,label}:{ok:boolean;label:string}){return <span className={`rounded-full px-2 py-1 text-[10px] font-semibold ${ok?"bg-sage/10 text-sage":"bg-brick/10 text-brick"}`}>{ok?"✓":"!"} {label}</span>}
export default function WorkersPage(){
 const [state,setState]=useState<SystemState|null>(null),[health,setHealth]=useState<HealthResponse|null>(null),[audit,setAudit]=useState<SystemRow[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[pending,setPending]=useState<{paused?:boolean;maintenance?:boolean}|null>(null); const s=loadSettings();
 const load=useCallback(async()=>{if(!s.baseUrl)return;try{const [a,b,c]=await Promise.all([fetchSystemState(s),fetchHealth(s),fetchAudit(s)]);setState(a);setHealth(b);setAudit(c.items.slice(0,8));setError(null)}catch(e){setError(e instanceof ApiError?e.message:"Could not load worker status.")}},[]);
 useEffect(()=>{load();const id=setInterval(load,5000);return()=>clearInterval(id)},[load]);
 const control=async(body:{paused?:boolean;maintenance?:boolean})=>{setBusy(true);try{setState(await updateSystemControl(s,body));await load()}catch(e){setError(e instanceof ApiError?e.message:"Action failed.")}finally{setBusy(false)}};
 const requestControl=(body:{paused?:boolean;maintenance?:boolean})=>setPending(body);
 return <AppShell><div className="h-full overflow-y-auto bg-paper px-8 py-6"><div className="mx-auto max-w-7xl"><header className="mb-6 flex items-end justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-ink/30">Control</p><h1 className="mt-1 font-display text-3xl font-semibold">Workers</h1><p className="mt-1 text-sm text-ink/45">Control worker release behavior and watch the active pipeline state.</p></div><button onClick={load} className="rounded-xl border border-line bg-white px-4 py-2.5 text-xs font-semibold text-ink/60 shadow-sm">Refresh</button></header>{error&&<div className="mb-5 rounded-xl border border-brick/20 bg-brick/10 px-4 py-3 text-sm text-brick">{error}</div>}
 <div className="mb-5 grid grid-cols-4 gap-3"><Card><p className="text-[10px] uppercase tracking-widest text-ink/35">Worker state</p><p className="mt-2 font-display text-2xl font-semibold">{state?.paused?"Paused":health?.processing?"Processing":"Ready"}</p></Card><Card><p className="text-[10px] uppercase tracking-widest text-ink/35">Queue depth</p><p className="mt-2 font-display text-2xl font-semibold">{health?.queue_depth??"—"}</p></Card><Card><p className="text-[10px] uppercase tracking-widest text-ink/35">Mode</p><p className="mt-2 font-display text-2xl font-semibold">{state?.maintenance?"Maintenance":"Live"}</p></Card><Card><p className="text-[10px] uppercase tracking-widest text-ink/35">Uptime</p><p className="mt-2 font-display text-2xl font-semibold">{health?`${Math.floor(health.uptime_seconds/3600)}h ${Math.floor((health.uptime_seconds%3600)/60)}m`:"—"}</p></Card></div>
 <div className="grid grid-cols-2 gap-4"><Card><h2 className="font-display font-semibold">Worker controls</h2><p className="mt-1 text-xs leading-relaxed text-ink/40">Pausing prevents new scans from being released. An already-running desktop job is not killed mid-run.</p><div className="mt-5 flex gap-2"><button disabled={busy} onClick={()=>requestControl({paused:!state?.paused})} className="rounded-xl bg-blueprint px-4 py-2.5 text-xs font-semibold text-paper disabled:opacity-40">{state?.paused?"Resume worker":"Pause worker"}</button><button disabled={busy} onClick={()=>requestControl({maintenance:!state?.maintenance})} className="rounded-xl border border-line px-4 py-2.5 text-xs font-semibold text-ink/60">{state?.maintenance?"Exit maintenance":"Maintenance mode"}</button></div></Card>
 <Card><h2 className="font-display font-semibold">Worker health</h2><div className="mt-4 flex flex-wrap gap-2"><Pill ok={health?.status!=="error"} label="API"/><Pill ok={!!health?.mongo_configured} label="Mongo configured"/><Pill ok={true} label="Queue"/><Pill ok={!!health?.tools?.python} label="Python runtime"/><Pill ok={!!health?.tools?.osascript} label="macOS automation"/></div></Card>
 <Card><h2 className="font-display font-semibold">Recent worker activity</h2><div className="mt-3 divide-y divide-line">{audit.length===0?<p className="py-6 text-xs text-ink/30">No worker control activity yet.</p>:audit.map((x,i)=><div key={i} className="flex gap-4 py-2.5 text-[11px]"><span className="w-36 shrink-0 font-mono text-ink/30">{new Date(x.at).toLocaleTimeString()}</span><b className="w-40 shrink-0 text-ink/60">{x.action}</b><span className="text-ink/45">{x.detail||"—"}</span></div>)}</div></Card>
 <Card><h2 className="font-display font-semibold">Release policy</h2><div className="mt-4 space-y-3 text-xs"><div className="flex justify-between rounded-xl bg-ink/[.03] px-4 py-3"><span className="text-ink/50">Automatic processing</span><b>Disabled</b></div><div className="flex justify-between rounded-xl bg-ink/[.03] px-4 py-3"><span className="text-ink/50">Manual release</span><b>Enabled</b></div><div className="flex justify-between rounded-xl bg-ink/[.03] px-4 py-3"><span className="text-ink/50">Active run interruption</span><b>Protected</b></div></div></Card></div></div></div><ConfirmModal open={!!pending} title={pending?.maintenance !== undefined ? (pending.maintenance ? "Enter maintenance mode?" : "Exit maintenance mode?") : (pending?.paused ? "Pause the worker?" : "Resume the worker?")} message={pending?.maintenance !== undefined ? (pending.maintenance ? "New scan releases will be blocked until maintenance mode is turned off. A job already running will finish." : "Normal worker controls will become available again.") : (pending?.paused ? "No new scan will be released while the worker is paused. An active desktop job will continue." : "The worker will be allowed to accept the next manually released scan.")} confirmLabel="Confirm action" busy={busy} onConfirm={()=>{if(!pending)return;const p=pending;setPending(null);void control(p)}} onCancel={()=>!busy&&setPending(null)} /></AppShell>;
}
