"use client";
import { useEffect, useMemo, useState } from "react";
import AppShell from "@/components/AppShell";
import ConfirmModal from "@/components/ConfirmModal";
import { ApiError, createAdmin, fetchAdmins, loadSettings, resendAdminInvitation, updateAdmin, type AdminRecord } from "@/lib/api";

const groups: Record<string,string> = { scans:"Scans", analytics:"Analytics", alerts:"Notifications", logs:"System logs", audit:"Audit logs", system:"System control", gam:"GAM", csv:"CSV importer", daz:"DAZ assets", admins:"Users & access" };
function groupFor(key:string){ return groups[key.split(".")[0]] ?? "Other"; }
function labelFor(key:string,label:string){ const overrides:Record<string,string>={"scans.process":"Process scans","scans.move":"Move scans between columns","scans.reorder":"Reorder queued cards","scans.retry":"Retry failed scans","scans.delete":"Delete scans","scans.deliver":"Retry result delivery"}; return overrides[key]??label; }

export default function AdminsPage(){
 const [admins,setAdmins]=useState<AdminRecord[]>([]); const [permissionOptions,setPermissionOptions]=useState<{key:string;label:string}[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [showCreate,setShowCreate]=useState(false); const [email,setEmail]=useState(""); const [selected,setSelected]=useState<string[]>([]); const [busy,setBusy]=useState(false); const [editing,setEditing]=useState<AdminRecord|null>(null); const [pending,setPending]=useState<{type:"disable"|"enable"|"resend";admin:AdminRecord}|null>(null);
 const load=async()=>{setLoading(true);try{const r=await fetchAdmins(loadSettings());setAdmins(r.items);setPermissionOptions(r.permissions);setError(null)}catch(e){setError(e instanceof ApiError?e.message:"Could not load administrator accounts.")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const grouped=useMemo(()=>permissionOptions.filter(x=>x.key!=="admins.manage").reduce<Record<string,typeof permissionOptions>>((a,x)=>{const g=groupFor(x.key);(a[g]??=[]).push(x);return a},{}),[permissionOptions]);
 const create=async()=>{if(busy)return;setBusy(true);try{await createAdmin(loadSettings(),{email:email.trim(),permissions:selected});setEmail("");setSelected([]);setShowCreate(false);await load()}catch(e){setError(e instanceof ApiError?e.message:"Could not create administrator or send invitation email.")}finally{setBusy(false)}};
 const savePermissions=async()=>{if(!editing||busy)return;setBusy(true);try{await updateAdmin(loadSettings(),editing.id,{permissions:selected});setEditing(null);await load()}catch(e){setError(e instanceof ApiError?e.message:"Could not update permissions.")}finally{setBusy(false)}};
 const apply=async()=>{if(!pending)return;setBusy(true);try{if(pending.type==="resend")await resendAdminInvitation(loadSettings(),pending.admin.id);else await updateAdmin(loadSettings(),pending.admin.id,{active:pending.type==="enable"});setPending(null);await load()}catch(e){setError(e instanceof ApiError?e.message:"Could not update account.")}finally{setBusy(false)}};
 const toggle=(key:string)=>setSelected(v=>v.includes(key)?v.filter(x=>x!==key):[...v,key]);
 const openEdit=(a:AdminRecord)=>{setEditing(a);setSelected(a.permissions)};
 return <AppShell><div className="h-full overflow-y-auto bg-paper px-8 py-6"><div className="mx-auto max-w-7xl"><header className="mb-6 flex items-end justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-ink/30">Admin</p><h1 className="mt-1 font-display text-3xl font-semibold">Users & access</h1><p className="mt-1 text-sm text-ink/45">Invite users by email and control exactly what they can see and do. Permissions are enforced on the server.</p></div><div className="flex gap-2"><button onClick={()=>void load()} className="rounded-xl border border-line bg-white px-4 py-2.5 text-xs font-semibold text-ink/60">Refresh</button><button onClick={()=>setShowCreate(v=>!v)} className="rounded-xl bg-blueprint px-4 py-2.5 text-xs font-semibold text-paper">{showCreate?"Close":"Invite user"}</button></div></header>{error&&<div className="mb-5 rounded-xl border border-brick/20 bg-brick/5 px-4 py-3 text-sm text-brick">{error}</div>}
 {showCreate&&<section className="mb-5 rounded-2xl border border-line bg-white p-5 shadow-sm"><h2 className="font-display font-semibold">Invite a user</h2><p className="mt-1 text-xs leading-5 text-ink/40">Enter their email address. They will receive a secure invitation and choose their own password. You never need to create or know their password.</p><label className="mt-4 block text-xs font-semibold text-ink/60">Email address<input type="email" value={email} onChange={e=>setEmail(e.target.value)} className="mt-2 w-full rounded-xl border border-line bg-paper px-3 py-2.5 text-sm font-normal outline-none focus:border-blueprint" placeholder="name@company.com"/></label><PermissionPicker groups={grouped} selected={selected} toggle={toggle}/><div className="mt-5 flex justify-end"><button disabled={busy||!email.trim()} onClick={()=>void create()} className="rounded-xl bg-blueprint px-5 py-2.5 text-xs font-semibold text-paper disabled:opacity-40">{busy?"Sending invitation…":"Create & send invitation"}</button></div></section>}
 <section className="rounded-2xl border border-line bg-white shadow-sm"><div className="border-b border-line px-5 py-4"><h2 className="font-display font-semibold">Accounts</h2><p className="mt-1 text-xs text-ink/40">{admins.length} account{admins.length===1?"":"s"}</p></div>{loading?<div className="p-6 space-y-4">{Array.from({length:4}).map((_,i)=><div key={i} className="h-20 animate-pulse rounded-xl bg-ink/[.04]"/>)}</div>:admins.length===0?<div className="px-5 py-12 text-center text-sm text-ink/40">No administrator accounts found.</div>:<div className="divide-y divide-line">{admins.map(a=><div key={a.id} className="px-5 py-4"><div className="flex items-center justify-between gap-5"><div className="min-w-0"><div className="flex items-center gap-2"><span className="font-display font-semibold">{a.email||a.username}</span>{a.is_super_admin&&<span className="rounded-full bg-blueprint/10 px-2 py-0.5 text-[9px] font-bold uppercase tracking-wider text-blueprint">Super admin</span>}<span className={`rounded-full px-2 py-0.5 text-[9px] font-bold uppercase tracking-wider ${a.invitation_pending?"bg-amber/10 text-amber":a.active?"bg-sage/10 text-sage":"bg-ink/5 text-ink/35"}`}>{a.invitation_pending?"Invitation pending":a.active?"Active":"Disabled"}</span></div><p className="mt-1 text-[10px] text-ink/35">{a.invitation_pending&&a.invitation_expires_at?`Invitation expires ${new Date(a.invitation_expires_at).toLocaleString()}`:`Last sign in: ${a.last_login_at?new Date(a.last_login_at).toLocaleString():"Never"}`}</p><div className="mt-2 flex flex-wrap gap-1">{a.is_super_admin?<span className="text-[10px] text-ink/45">All permissions</span>:a.permissions.length?a.permissions.map(p=><span key={p} className="rounded-md bg-paper px-2 py-1 font-mono text-[9px] text-ink/45">{p}</span>):<span className="text-[10px] text-ink/35">No permissions assigned</span>}</div></div><div className="flex shrink-0 gap-2">{!a.is_super_admin&&<><button onClick={()=>openEdit(a)} className="rounded-lg border border-line px-3 py-2 text-[10px] font-semibold text-ink/55">Permissions</button>{a.invitation_pending?<button onClick={()=>setPending({type:"resend",admin:a})} className="rounded-lg border border-line px-3 py-2 text-[10px] font-semibold text-ink/55">Resend invite</button>:<button onClick={()=>setPending({type:a.active?"disable":"enable",admin:a})} className="rounded-lg border border-line px-3 py-2 text-[10px] font-semibold text-ink/55">{a.active?"Disable":"Enable"}</button>}</>}</div></div></div>)}</div>}</section></div></div>
 <ConfirmModal open={!!pending} title={pending?.type==="resend"?"Resend invitation?":pending?.type==="disable"?"Disable this user?":"Enable this user?"} message={pending?.type==="resend"?`A new 24-hour password setup link will be sent to ${pending.admin.email}. The previous unused invitation will be invalidated.`:pending?.type==="disable"?"This account will be denied on every authenticated request.":"This account will be allowed to sign in again with its existing permissions."} confirmLabel={pending?.type==="resend"?"Resend invitation":pending?.type==="disable"?"Disable account":"Enable account"} busy={busy} onCancel={()=>!busy&&setPending(null)} onConfirm={()=>void apply()}/>
 {editing&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-blueprint/25 p-6"><div className="max-h-[90vh] w-[760px] overflow-y-auto rounded-2xl border border-line bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-ink/30">Access policy</p><h2 className="mt-1 font-display text-xl font-semibold">Permissions for {editing.email}</h2><p className="mt-1 text-xs text-ink/40">Each action is independently enforced by the backend.</p></div><button onClick={()=>setEditing(null)} className="text-ink/35">×</button></div><PermissionPicker groups={grouped} selected={selected} toggle={toggle}/><div className="mt-5 flex justify-end gap-2"><button onClick={()=>setEditing(null)} className="rounded-xl border border-line px-4 py-2.5 text-xs font-semibold">Cancel</button><button disabled={busy} onClick={()=>void savePermissions()} className="rounded-xl bg-blueprint px-5 py-2.5 text-xs font-semibold text-paper">{busy?"Saving…":"Save permissions"}</button></div></div></div>}</AppShell>;
}
function PermissionPicker({groups,selected,toggle}:{groups:Record<string,{key:string;label:string}[]>;selected:string[];toggle:(key:string)=>void}){return <div className="mt-5 space-y-4">{Object.entries(groups).map(([group,items])=><div key={group}><p className="text-[10px] font-bold uppercase tracking-[.16em] text-ink/30">{group}</p><div className="mt-2 grid grid-cols-2 gap-2">{items.map(x=><button key={x.key} type="button" onClick={()=>toggle(x.key)} className={`flex items-center justify-between rounded-xl border px-3 py-2.5 text-left text-xs ${selected.includes(x.key)?"border-blueprint bg-blueprint/5":"border-line bg-white"}`}><span>{labelFor(x.key,x.label)}</span><span className={`font-mono text-[9px] ${selected.includes(x.key)?"text-blueprint":"text-ink/25"}`}>{selected.includes(x.key)?"GRANTED":"—"}</span></button>)}</div></div>)}</div>}
