"use client";
import { useEffect, useState } from "react";
import AppShell from "@/components/AppShell";
import ConfirmModal from "@/components/ConfirmModal";
import { ApiError, createAdmin, fetchAdmins, loadSettings, updateAdmin, type AdminRecord } from "@/lib/api";
export default function AdminsPage(){
  const [admins,setAdmins]=useState<AdminRecord[]>([]); const [permissionOptions,setPermissionOptions]=useState<{key:string;label:string}[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [showCreate,setShowCreate]=useState(false); const [pending,setPending]=useState<{type:"disable"|"enable"|"password";admin:AdminRecord}|null>(null); const [username,setUsername]=useState(""); const [password,setPassword]=useState(""); const [selected,setSelected]=useState<string[]>([]); const [newPassword,setNewPassword]=useState(""); const [busy,setBusy]=useState(false);
  const load=async()=>{setLoading(true);try{const r=await fetchAdmins(loadSettings());setAdmins(r.items);setPermissionOptions(r.permissions);setError(null)}catch(e){setError(e instanceof ApiError?e.message:"Could not load administrator accounts.")}finally{setLoading(false)}}; useEffect(()=>{load()},[]);
  const resetForm=()=>{setUsername("");setPassword("");setSelected([]);setShowCreate(false)};
  const create=async()=>{if(busy)return;setBusy(true);try{await createAdmin(loadSettings(),{username:username.trim(),password,permissions:selected});resetForm();await load()}catch(e){setError(e instanceof ApiError?e.message:"Could not create administrator.")}finally{setBusy(false)}};
  const apply=async()=>{if(!pending)return;setBusy(true);try{if(pending.type==="password")await updateAdmin(loadSettings(),pending.admin.id,{password:newPassword});else await updateAdmin(loadSettings(),pending.admin.id,{active:pending.type==="enable"});setPending(null);setNewPassword("");await load()}catch(e){setError(e instanceof ApiError?e.message:"Could not update administrator.")}finally{setBusy(false)}};
  const togglePermission=(key:string)=>setSelected(v=>v.includes(key)?v.filter(x=>x!==key):[...v,key]);
  return <AppShell><div className="h-full overflow-y-auto bg-paper px-8 py-6"><div className="mx-auto max-w-7xl"><header className="mb-6 flex items-end justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-ink/30">Admin</p><h1 className="mt-1 font-display text-3xl font-semibold">Administrator accounts</h1><p className="mt-1 text-sm text-ink/45">Create operators with least-privilege access. Super admin is protected from accidental disablement.</p></div><div className="flex gap-2"><button onClick={load} className="rounded-xl border border-line bg-white px-4 py-2.5 text-xs font-semibold text-ink/60">Refresh</button><button onClick={()=>setShowCreate(v=>!v)} className="rounded-xl bg-blueprint px-4 py-2.5 text-xs font-semibold text-paper">{showCreate?"Close":"Add admin"}</button></div></header>{error&&<div className="mb-5 rounded-xl border border-brick/20 bg-brick/5 px-4 py-3 text-sm text-brick">{error}</div>}
  {showCreate&&<section className="mb-5 rounded-2xl border border-line bg-white p-5 shadow-sm"><div className="mb-4"><h2 className="font-display font-semibold">Create administrator</h2><p className="mt-1 text-xs text-ink/40">Passwords are hashed server-side and never returned to the dashboard.</p></div><div className="grid grid-cols-2 gap-4"><label className="text-xs font-semibold text-ink/60">Username<input value={username} onChange={e=>setUsername(e.target.value)} className="mt-2 w-full rounded-xl border border-line bg-paper px-3 py-2.5 text-sm font-normal outline-none focus:border-blueprint" placeholder="operator-01"/></label><label className="text-xs font-semibold text-ink/60">Temporary password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-2 w-full rounded-xl border border-line bg-paper px-3 py-2.5 text-sm font-normal outline-none focus:border-blueprint" placeholder="Minimum 14 characters"/></label></div><div className="mt-5"><p className="text-xs font-semibold text-ink/60">Permissions</p><div className="mt-2 grid grid-cols-2 gap-2">{permissionOptions.filter(x=>x.key!=="admins.manage").map(x=><button key={x.key} onClick={()=>togglePermission(x.key)} className={`flex items-center justify-between rounded-xl border px-3 py-2.5 text-left text-xs ${selected.includes(x.key)?"border-blueprint bg-blueprint/5":"border-line bg-white"}`}><span>{x.label}</span><span className="font-mono text-[9px] opacity-45">{selected.includes(x.key)?"GRANTED":"—"}</span></button>)}</div></div><div className="mt-5 flex justify-end"><button disabled={busy||!username||password.length<14} onClick={create} className="rounded-xl bg-blueprint px-5 py-2.5 text-xs font-semibold text-paper disabled:opacity-40">{busy?"Creating…":"Create admin"}</button></div></section>}
  <section className="rounded-2xl border border-line bg-white shadow-sm"><div className="border-b border-line px-5 py-4"><h2 className="font-display font-semibold">Accounts</h2><p className="mt-1 text-xs text-ink/40">{admins.length} administrator account{admins.length===1?"":"s"}</p></div>{loading?<div className="p-8 text-center text-xs text-ink/40">Loading accounts…</div>:<div className="divide-y divide-line">{admins.map(a=><div key={a.id} className="px-5 py-4"><div className="flex items-center justify-between gap-4"><div className="min-w-0"><div className="flex items-center gap-2"><span className="font-display font-semibold">{a.username}</span>{a.is_super_admin&&<span className="rounded-full bg-blueprint/10 px-2 py-0.5 text-[9px] font-bold uppercase tracking-wider text-blueprint">Super admin</span>}<span className={`rounded-full px-2 py-0.5 text-[9px] font-bold uppercase tracking-wider ${a.active?"bg-sage/10 text-sage":"bg-ink/5 text-ink/35"}`}>{a.active?"Active":"Disabled"}</span></div><p className="mt-1 text-[10px] text-ink/35">Last sign in: {a.last_login_at?new Date(a.last_login_at).toLocaleString():"Never"}</p><div className="mt-2 flex flex-wrap gap-1">{a.is_super_admin?<span className="text-[10px] text-ink/45">All permissions</span>:a.permissions.map(p=><span key={p} className="rounded-md bg-paper px-2 py-1 font-mono text-[9px] text-ink/45">{p}</span>)}</div></div><div className="flex shrink-0 gap-2">{!a.is_super_admin&&<><button onClick={()=>setPending({type:a.active?"disable":"enable",admin:a})} className="rounded-lg border border-line px-3 py-2 text-[10px] font-semibold text-ink/55">{a.active?"Disable":"Enable"}</button><button onClick={()=>setPending({type:"password",admin:a})} className="rounded-lg border border-line px-3 py-2 text-[10px] font-semibold text-ink/55">Reset password</button></>}</div></div></div>)}</div>}</section>
  </div></div><ConfirmModal open={!!pending} title={pending?.type==="password"?"Reset administrator password?":pending?.type==="disable"?"Disable this administrator?":"Enable this administrator?"} message={pending?.type==="password"?"The existing password will stop working immediately after the new password is saved.":pending?.type==="disable"?"This account will no longer be able to start a new session. Existing sessions remain time-limited but the account is checked on every request.":"This administrator will regain access using the permissions already assigned."} confirmLabel={pending?.type==="password"?"Reset password":pending?.type==="disable"?"Disable account":"Enable account"} busy={busy} onCancel={()=>{if(!busy){setPending(null);setNewPassword("")}}} onConfirm={()=>void apply()}>{pending?.type==="password"&&<input autoFocus type="password" value={newPassword} onChange={e=>setNewPassword(e.target.value)} placeholder="New password — minimum 14 characters" className="mt-4 w-full rounded-xl border border-line bg-paper px-3 py-2.5 text-sm outline-none focus:border-blueprint"/>}</ConfirmModal></AppShell>;
}
