"use client";
import { useCallback, useEffect, useState } from "react";
import AppShell from "@/components/AppShell";
import ConnectionSettingsPanel, { type ConnectionStatus } from "@/components/ConnectionSettings";
import ConfirmModal from "@/components/ConfirmModal";
import { ApiError, fetchHealth, fetchSystemState, loadSettings, runDiagnostics, saveSettings, updateFeatures, updateSystemConfig, type ConnectionSettings, type HealthResponse, type SystemState } from "@/lib/api";
const featureLabels:Record<string,string>={manual_processing:"Manual processing",drag_drop:"Drag & drop",auto_retry:"Automatic retry",priority_queue:"Priority queue",analytics:"Analytics",failure_alerts:"Failure alerts"};
const configLabels:Record<string,string>={worker_concurrency:"Worker concurrency",refresh_interval_seconds:"Refresh interval (sec)",max_retries:"Max retries",photoshop_timeout_seconds:"Photoshop timeout (sec)",illustrator_timeout_seconds:"Illustrator timeout (sec)",daz_timeout_seconds:"Daz timeout (sec)"};
function Card({children}:{children:React.ReactNode}){return <section className="rounded-2xl border border-line bg-white p-5 shadow-sm">{children}</section>}
export default function SystemPage(){const [state,setState]=useState<SystemState|null>(null),[health,setHealth]=useState<HealthResponse|null>(null),[settings,setSettings]=useState<ConnectionSettings>({baseUrl:"",apiKey:""}),[diag,setDiag]=useState<{name:string;ok:boolean}[]|null>(null),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false),[pending,setPending]=useState<{kind:string;key?:string;value?:boolean}|null>(null);useEffect(()=>setSettings(loadSettings()),[]);const load=useCallback(async()=>{const s=loadSettings();if(!s.baseUrl)return;try{const [a,b]=await Promise.all([fetchSystemState(s),fetchHealth(s)]);setState(a);setHealth(b);setError(null)}catch(e){setError(e instanceof ApiError?e.message:"Could not load system settings.")}},[]);useEffect(()=>{load()},[load]);const control=async(k:string,v:boolean)=>{try{setState(await updateFeatures(loadSettings(),{[k]:v}))}catch(e){setError(e instanceof ApiError?e.message:"Feature update failed.")}};const saveConfig=async()=>{if(!state)return;try{setState(await updateSystemConfig(loadSettings(),state.config))}catch(e){setError(e instanceof ApiError?e.message:"Configuration update failed.")}};const diagnostics=async()=>{setBusy(true);try{setDiag((await runDiagnostics(loadSettings())).checks)}catch(e){setError(e instanceof ApiError?e.message:"Diagnostics failed.")}finally{setBusy(false)}};const connectionStatus:ConnectionStatus=health?.status==="ok"?"ok":settings.baseUrl?"error":"disconnected";const save=(s:ConnectionSettings)=>{saveSettings(s);setSettings(s);load()};
 const confirmPending=async()=>{if(!pending)return;const p=pending;setPending(null);if(p.kind.startsWith("feature:")){await control(p.key!,p.value!);return}await saveConfig();};return <AppShell><div className="h-full overflow-y-auto bg-paper px-8 py-6"><div className="mx-auto max-w-7xl"><header className="mb-6 flex items-end justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-ink/30">Admin</p><h1 className="mt-1 font-display text-3xl font-semibold">System settings</h1><p className="mt-1 text-sm text-ink/45">Connection, runtime configuration, feature flags and diagnostics.</p></div><button onClick={load} className="rounded-xl border border-line bg-white px-4 py-2.5 text-xs font-semibold text-ink/60 shadow-sm">Refresh</button></header>{error&&<div className="mb-5 rounded-xl border border-brick/20 bg-brick/10 px-4 py-3 text-sm text-brick">{error}</div>}
 <div className="grid grid-cols-2 gap-4"><Card><div className="mb-4"><h2 className="font-display font-semibold">Backend connection</h2><p className="mt-1 text-xs text-ink/40">Configure the backend endpoint used by the authenticated desktop dashboard.</p></div><ConnectionSettingsPanel settings={settings} status={connectionStatus} onSave={save}/></Card>
 <Card><div className="flex items-center justify-between"><div><h2 className="font-display font-semibold">Diagnostics</h2><p className="text-xs text-ink/40">Run live checks against API, MongoDB, queue and worker.</p></div><button disabled={busy||!settings.baseUrl} onClick={diagnostics} className="rounded-lg border border-line px-3 py-2 text-[11px] font-semibold text-ink/60 disabled:opacity-40">Run full diagnostic</button></div>{diag&&<div className="mt-4 grid grid-cols-2 gap-2">{diag.map(x=><div key={x.name} className={`rounded-xl px-3 py-2 text-xs font-semibold ${x.ok?"bg-sage/10 text-sage":"bg-brick/10 text-brick"}`}>{x.ok?"✓":"!"} {x.name}</div>)}</div>}</Card>
 <Card><h2 className="font-display font-semibold">Feature flags</h2><p className="mt-1 text-xs text-ink/40">Turn optional operational capabilities on or off without editing source code.</p><div className="mt-4 grid grid-cols-2 gap-2">{state&&Object.entries(state.features).map(([k,v])=><button key={k} onClick={()=>setPending({kind:`feature:${k}`,key:k,value:!v})} className="flex items-center justify-between rounded-xl border border-line px-3 py-3 text-xs"><span>{featureLabels[k]??k}</span><span className={`rounded-full px-2 py-0.5 text-[10px] font-semibold ${v?"bg-sage/10 text-sage":"bg-ink/5 text-ink/35"}`}>{v?"ON":"OFF"}</span></button>)}</div></Card>
 <Card><div className="flex items-center justify-between"><div><h2 className="font-display font-semibold">Runtime configuration</h2><p className="text-xs text-ink/40">Safe runtime settings. Secrets and source code remain protected.</p></div><button onClick={()=>setPending({kind:"config"})} className="rounded-lg bg-blueprint px-3 py-2 text-[11px] font-semibold text-paper">Save</button></div><div className="mt-4 grid grid-cols-2 gap-3">{state&&Object.entries(state.config).map(([k,v])=><label key={k} className="text-xs text-ink/55">{configLabels[k]??k}<input type="number" min="0" value={v} onChange={e=>setState({...state,config:{...state.config,[k]:Number(e.target.value)}})} className="mt-1 w-full rounded-lg border border-line bg-paper px-3 py-2 font-mono text-xs outline-none focus:border-blueprint"/></label>)}</div></Card>
 </div><ConfirmModal open={!!pending} title={pending?.kind.startsWith("feature:")?"Change this feature?":"Save runtime configuration?"} message={pending?.kind.startsWith("feature:")?"This changes an operational capability for the live dashboard. Confirm before applying the change.":"These runtime values will apply to the running backend. Review the values before saving."} confirmLabel="Apply change" busy={busy} onConfirm={()=>void confirmPending()} onCancel={()=>!busy&&setPending(null)} /><p className="mt-5 text-[11px] text-ink/30">Platform: {health?.platform??"—"} · Python: {health?.python??"—"} · Mongo configured: {health?.mongo_configured?"yes":"no"}</p></div></div></AppShell>}
