"use client";
import type { ReactNode } from "react";
import { useCallback, useEffect, useState } from "react";
import { ApiError, fetchAudit, fetchHealth, fetchLogs, fetchSystemState, loadSettings, runDiagnostics, updateFeatures, updateSystemConfig, updateSystemControl, type HealthResponse, type SystemRow, type SystemState } from "@/lib/api";
const featureLabels: Record<string,string>={manual_processing:"Manual processing",drag_drop:"Drag & drop",auto_retry:"Automatic retry",priority_queue:"Priority queue",analytics:"Analytics",failure_alerts:"Failure alerts"};
const configLabels: Record<string,string>={worker_concurrency:"Worker concurrency",refresh_interval_seconds:"Refresh interval (sec)",max_retries:"Max retries",photoshop_timeout_seconds:"Photoshop timeout (sec)",illustrator_timeout_seconds:"Illustrator timeout (sec)",daz_timeout_seconds:"Daz timeout (sec)"};
function Card({children,className=""}:{children:ReactNode;className?:string}){return <section className={`rounded-2xl border border-line bg-white p-5 shadow-sm ${className}`}>{children}</section>}
function Pill({ok,label}:{ok:boolean;label:string}){return <span className={`rounded-full px-2 py-1 text-[10px] font-semibold ${ok?"bg-sage/10 text-sage":"bg-brick/10 text-brick"}`}>{ok?"✓":"!"} {label}</span>}
export default function SystemPage(){
 const [state,setState]=useState<SystemState|null>(null); const [health,setHealth]=useState<HealthResponse|null>(null); const [audit,setAudit]=useState<SystemRow[]>([]); const [logs,setLogs]=useState<SystemRow[]>([]); const [level,setLevel]=useState("all"); const [diag,setDiag]=useState<{name:string;ok:boolean}[]|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null); const s=loadSettings();
 const load=useCallback(async()=>{if(!s.baseUrl)return;try{const [a,b,c,d]=await Promise.all([fetchSystemState(s),fetchHealth(s),fetchAudit(s),fetchLogs(s,level)]);setState(a);setHealth(b);setAudit(c.items);setLogs(d.items);setError(null)}catch(e){setError(e instanceof ApiError?e.message:"Could not load system controls.")}},[level]);
 useEffect(()=>{load()},[load]);
 const control=async(body:{paused?:boolean;maintenance?:boolean})=>{setBusy(true);try{setState(await updateSystemControl(s,body));await load()}catch(e){setError(e instanceof ApiError?e.message:"Action failed.")}finally{setBusy(false)}};
 const feature=async(k:string,v:boolean)=>{try{setState(await updateFeatures(s,{[k]:v}))}catch(e){setError(e instanceof ApiError?e.message:"Feature update failed.")}};
 const saveConfig=async()=>{if(!state)return;try{setState(await updateSystemConfig(s,state.config))}catch(e){setError(e instanceof ApiError?e.message:"Configuration update failed.")}};
 const diagnostics=async()=>{setBusy(true);try{setDiag((await runDiagnostics(s)).checks);await load()}catch(e){setError(e instanceof ApiError?e.message:"Diagnostics failed.")}finally{setBusy(false)}};
 return <main className="min-h-screen bg-paper px-6 py-6"><div className="mx-auto max-w-7xl">
  <header className="mb-6 flex items-end justify-between"><div><a href="/" className="text-[11px] font-medium text-blueprint hover:underline">← Pipeline board</a><h1 className="mt-2 font-display text-3xl font-semibold">System control center</h1><p className="mt-1 text-sm text-ink/45">Operate the PICD pipeline without leaving the dashboard.</p></div><button onClick={load} className="rounded-xl border border-line bg-white px-4 py-2.5 text-xs font-semibold text-ink/60 shadow-sm hover:border-blueprint hover:text-blueprint">Refresh</button></header>
  {error&&<div className="mb-5 rounded-xl border border-brick/20 bg-brick/10 px-4 py-3 text-sm text-brick">{error}</div>}
  <div className="mb-5 grid grid-cols-4 gap-3"><Card><p className="text-[10px] uppercase tracking-widest text-ink/35">Worker</p><p className="mt-2 font-display text-2xl font-semibold">{state?.paused?"Paused":health?.processing?"Running":"Ready"}</p></Card><Card><p className="text-[10px] uppercase tracking-widest text-ink/35">Queue</p><p className="mt-2 font-display text-2xl font-semibold">{health?.queue_depth??"—"}</p></Card><Card><p className="text-[10px] uppercase tracking-widest text-ink/35">Uptime</p><p className="mt-2 font-display text-2xl font-semibold">{health?`${Math.floor(health.uptime_seconds/3600)}h ${Math.floor((health.uptime_seconds%3600)/60)}m`:"—"}</p></Card><Card><p className="text-[10px] uppercase tracking-widest text-ink/35">Mode</p><p className="mt-2 font-display text-2xl font-semibold">{state?.maintenance?"Maintenance":"Live"}</p></Card></div>
  <div className="grid grid-cols-2 gap-4">
   <Card><h2 className="font-display font-semibold">Worker controls</h2><p className="mt-1 text-xs text-ink/40">Pause new releases or enter maintenance without interrupting an active desktop run.</p><div className="mt-4 flex gap-2"><button disabled={busy} onClick={()=>control({paused:!state?.paused})} className="rounded-xl bg-blueprint px-4 py-2.5 text-xs font-semibold text-paper disabled:opacity-40">{state?.paused?"Resume worker":"Pause worker"}</button><button disabled={busy} onClick={()=>control({maintenance:!state?.maintenance})} className="rounded-xl border border-line px-4 py-2.5 text-xs font-semibold text-ink/60">{state?.maintenance?"Exit maintenance":"Maintenance mode"}</button></div></Card>
   <Card><h2 className="font-display font-semibold">System health</h2><div className="mt-4 flex flex-wrap gap-2"><Pill ok={health?.status!=="error"} label="API"/><Pill ok={!!health?.mongo_configured} label="Mongo configured"/><Pill ok={true} label="Queue"/><Pill ok={true} label={`Python ${health?.python??"—"}`}/></div></Card>
   <Card><h2 className="font-display font-semibold">Feature flags</h2><p className="mt-1 text-xs text-ink/40">Operational capabilities can be toggled without editing source.</p><div className="mt-4 grid grid-cols-2 gap-2">{state&&Object.entries(state.features).map(([k,v])=><button key={k} onClick={()=>feature(k,!v)} className="flex items-center justify-between rounded-xl border border-line px-3 py-2 text-xs"><span>{featureLabels[k]??k}</span><span className={`rounded-full px-2 py-0.5 text-[10px] font-semibold ${v?"bg-sage/10 text-sage":"bg-ink/5 text-ink/35"}`}>{v?"ON":"OFF"}</span></button>)}</div></Card>
   <Card><div className="flex items-center justify-between"><div><h2 className="font-display font-semibold">Pipeline configuration</h2><p className="text-xs text-ink/40">Runtime-safe settings; secrets and source code remain protected.</p></div><button onClick={saveConfig} className="rounded-lg bg-blueprint px-3 py-2 text-[11px] font-semibold text-paper">Save</button></div><div className="mt-4 grid grid-cols-2 gap-3">{state&&Object.entries(state.config).map(([k,v])=><label key={k} className="text-xs text-ink/55">{configLabels[k]??k}<input type="number" min="0" value={v} onChange={e=>setState({...state,config:{...state.config,[k]:Number(e.target.value)}})} className="mt-1 w-full rounded-lg border border-line bg-paper px-3 py-2 font-mono text-xs outline-none focus:border-blueprint"/></label>)}</div></Card>
   <Card><div className="flex items-center justify-between"><div><h2 className="font-display font-semibold">Diagnostics</h2><p className="text-xs text-ink/40">Run a live service and database check.</p></div><button disabled={busy} onClick={diagnostics} className="rounded-lg border border-line px-3 py-2 text-[11px] font-semibold text-ink/60">Run full diagnostic</button></div>{diag&&<div className="mt-4 flex flex-wrap gap-2">{diag.map(x=><Pill key={x.name} ok={x.ok} label={x.name}/>)}</div>}</Card>
   <Card><div className="flex items-center justify-between"><h2 className="font-display font-semibold">Logs</h2><select value={level} onChange={e=>setLevel(e.target.value)} className="rounded-lg border border-line bg-white px-2 py-1.5 text-xs"><option value="all">All</option><option value="info">Info</option><option value="error">Errors</option></select></div><div className="mt-3 max-h-64 overflow-auto rounded-xl bg-ink/[.03]">{logs.slice(0,40).map((x,i)=><div key={i} className="border-b border-line px-3 py-2 text-[11px]"><span className="font-mono text-ink/30">{new Date(x.at).toLocaleTimeString()}</span> <span className={x.level==="error"?"text-brick":"text-ink/65"}>{x.detail}</span></div>)}</div></Card>
  </div>
  <Card className="mt-4"><h2 className="font-display font-semibold">Audit trail</h2><div className="mt-3 max-h-72 overflow-auto">{audit.length===0?<p className="py-6 text-center text-xs text-ink/30">No control actions recorded yet.</p>:audit.map((x,i)=><div key={i} className="flex gap-4 border-b border-line py-2 text-[11px]"><span className="w-36 shrink-0 font-mono text-ink/30">{new Date(x.at).toLocaleString()}</span><b className="w-40 shrink-0 text-ink/60">{x.action}</b><span className="text-ink/45">{x.detail||"—"}</span></div>)}</div></Card>
 </div></main>
}
